version: '3.8'

services:
  proxy:
    build: ./
    networks:
      - example1
      - example2
    ports:
      - 80:80
      - 443:443

networks:
  example1:
    external:
      name: example1_default
  example2:
    external:
      name: example2_default